project:
  type: website
  output-dir: docs/

website:
  title: "Camille Landesvatter | Quantitative Researcher"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - portfolio.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



