---
title: "Projects"
---

For the latest overview on which projects I am working on recently, please also refer to my <a href="https://github.com/clandesv" target="_blank">GitHub Account</a>.

### APIs for Social Scientists: A collaborative review

Together with students and researchers from the University of Mannheim and beyond, I created a comprehensive **introduction that explores how social scientists can leverage APIs to address significant research questions**. This introduction covers various use cases such as data collection and data manipulation but also a chapter on Authentication and other Best Practices for API usage. Together with my Co-Editors, I was responsible for the **project management and coordination of over 20 researchers working together on this project**.

The project is ongoing, and you can find the **latest version** <a href="https://paulcbauer.github.io/apis_for_social_scientists_a_review/" target="_blank">here</a>.

To create further resources out of our work, I collaborated with the <a href="
https://www.mzes.uni-mannheim.de/socialsciencedatalab/" target="_blank">MZES Social Science Data Lab</a> to organize a **roundtable event** where together with co-editors and co-authors we reported on our experiences. You can watch the event on <a href="https://www.youtube.com/watch?v=Jd8NtdeQPCc&t=553s" target="_blank">YouTube</a>.

### A 2-day Workshop on Computational Social Science

<i>tba.</i>

<!-- Together with colleagues from the Mannheim Centre for European Social Research (MZES), we secured extensive funding for organizing and conducting **a 2-day workshop on Computational Social Science**. -->

### How do Social Scientists Visualize?

<i>tba.</i>

Together with a colleague from the University of Freiburg and LMU Munich, and our student research assistant at the University of Mannheim, we are working on a project where we classify a large database of data visualizations created by social scientists. Our aim is to identify key characteristics and features of these visualizations to learn about the state of the art in social science data visualization and the level of complexity currently given in this field.

At the moment, I am responsible for developing a **Shiny App with R** which will be used to manually annotate all visualizations in the database.

More updates will follow for this project as we continue.

<!-- We are also planning to conduct descriptive statistics as well as machine learning to learn about promiment features in the visualizations and to predict how they influence for example the complexity of a plot. Ultimately, we are talking abotu how we could train a model -->



